[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_1 = "9qfovSZQtZ3VkgCTiDDWuMCpkPyxt3HAcHh19MiX6pGU"
day_10 = "BpiMzk7hQDZEm1HKNCQnN8BrUkUYBbY9Jmni8gv9qcvj"
day_10_1 = "Hya7FfvnDRhEB1cRNZAtfeu5TVjxCJR1BEQK81btLUCs"
day_11 = "2SCX7gj5ByjWvin16BNNDjZxEcsikX15DWMMccc7EVXD"
day_12 = "8FErGg2jmveugDusoUAwtNw6HWzCHkBtmjc555tcHCcF"
day_12_1 = "DHWYP8ts4Sqowwt7n268JEoigySQyA3VGndRTwqb2xeE"
day_12_a = "CphRuTfdEURRPQwXmBxrsy1Bupfnib1pEmJzKGzEAV2t"
day_13 = "BiWQLQ2PHD34Ynsmn4RcVw3dccmzq3Wv8r8Gds9pGujq"
day_14 = "J3h97qKEjawFyr7iypKL27kutnbkTkaCuwd4szvJPYdD"
day_2 = "7HppZVRYrPDPMUg7VK6U1zsTqVvjtNbDve6k6Y7kZVoo"
day_3 = "6jkFHps8UYy4g1cEoxWpmpgxW77DX5fV27aqRSJQA7xZ"
day_3_1 = "DvF8picaK3cuoQgK8CdChqRm95soPUwRGSDpmbFguffL"
day_4 = "5q5xqHhCFFtLpBSL7byhLihBdcjXZYDqjyfB8QZE4BGR"
day_5 = "F1FxMXxpFuboFN2wACE8JUaYGEE4TjqHhR8dS9EZ3jQt"
day_6 = "BnV6jJjxmxsfjrzDic4dNuz1a9Gyos18adaMgDt4a7ya"
day_7 = "2e9RkrSUUS2b4vE5VzrkQiqtRKPTnfGXedKbcNzFLsdn"
day_7_1 = "AhQCWsaR5GsDZGd7xXD9G3ESLvTmtepbuJnMHPJzx3P9"
day_8 = "DnAyn23aQJC3LL74G1FHwksnHCoFyefNNRchHjWgHc79"
test1 = "EMm23Ufno7DoB8U1Fa91EsL6b3UvyEEBqAWGqyLjBGRo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
