[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_1 = "5oSSkEc2gZS9mZRMsw4iyapeRtQRchnAUuiUzkeiCNqn"
day_2 = "BGGkzgeCXkyC6xWcEyvJ8Geb9davsUQbZAkjV85tHuQD"
day_3 = "8cK7F1Ku3aFduYUUUE79Ad5WDkQGFM6jC6pUSeiPjzeT"
day_3_1 = "49zJroisjGYVCBnnwRav9bCGScxLqhpw4dvPGhYbfWkU"
day_4 = "FtRZjdbYvZVW59CVSe94F6XiaahpCuEuByJqw4bH9Ray"
day_5 = "HNdiq7jWsmQ33GPmRd95NR3Momr8pcUVx3GB7MuJMhU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
