[workspace]
members = ["programs/*", "rust_projects/day_8_1"]
resolver = "2"

[profile.release]
# overflow-checks = false
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
